### ISSUE TITLE
Web service is currently down

### ISSUE THREAD

**Issue by yevgenko** [davidmoten/xsd-forms#16]
Just noticed that xsd-forms web service is down
http://xsd-forms-generator.xuml-tools.cloudbees.net/

![apache_tomcat_6_0_39_-_error_report](https://cloud.githubusercontent.com/assets/62760/6715249/507adab6-cdae-11e4-9def-a0c55aa6d9c9.png)

**Comment by davidmoten** [comment]
Thanks, yeah cloud bees pulled their service. I thought to move it to
Heroku. I'll note here when done.

**Comment by davidmoten** [comment]
app moved to https://xsd-forms.herokuapp.com/
