### ISSUE TITLE
Non-resolvable parent POM

### ISSUE THREAD

**Issue by chetna-code** [davidmoten/xsd-forms#33]
I am trying to setup xsd to html form to my local machine but I am getting below error

ps note: I am not much aware in java and maven framework

D:\chetna\chetna\xsd-forms-master>mvn clean install
[INFO] Scanning for projects...
Downloading from central: https://repo.maven.apache.org/maven2/org/sonatype/oss/oss-parent/7/oss-parent-7.pom
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[FATAL] Non-resolvable parent POM for com.github.davidmoten.xsdforms:xsd-forms:0.2.2-SNAPSHOT: Could not transfer artifact org.sonatype.oss:oss-parent:pom:7 from/to central (https://repo.maven.apache.org/maven2): This is usually a temporary error during hostname resolution and means that the local server did not receive a response from an authoritative server (repo.maven.apache.org) and 'parent.relativePath' points at wrong local POM @ line 4, column 10
 @
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]
[ERROR]   The project com.github.davidmoten.xsdforms:xsd-forms:0.2.2-SNAPSHOT (D:\chetna\chetna\xsd-forms-master\pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM for com.github.davidmoten.xsdforms:xsd-forms:0.2.2-SNAPSHOT: Could not transfer artifact org.sonatype.oss:oss-parent:pom:7 from/to central (https://repo.maven.apache.org/maven2): This is usually a temporary error during hostname resolution and means that the local server did not receive a response from an authoritative server (repo.maven.apache.org) and 'parent.relativePath' points at wrong local POM @ line 4, column 10 -> [Help 2]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/UnresolvableModelException

D:\chetna\chetna\xsd-forms-master>

**Comment by davidmoten** [comment]
You need an internet connection of course. It tells you the link it couldn't download. I just tried it and is fine. Please try again.

**Comment by chetna-code** [comment]
Dear David,

Thank you so much for your quick Response

Internet connect is working fine but I think I am using corporate Internet
with proxy setting and also VPN so Can it cause the issue ?


Regards,
Chetna

**Comment by davidmoten** [comment]
Yeah that would be it. You need to put your proxy information in .m2/settings.xml. Google it. Good luck.

**Comment by chetna-code** [comment]
Hi David,

Thank you so much for your support. It's working now in my local machine

BR
Chetna
